#!/bin/dash -f

export WMII_TERM="urxvtc"

. session.sh

local_events () {
	cat <<'!'
# Events
Event DestroyTag
	wmiir remove "/lbar/$@"
	rm -rf "$(wmiir namespace)/$@"
Event OpenPDF
	wi_tabbed_open_tab $WI_PDF "$@"
Event OpenURL
	wi_tabbed_open_tab $WI_URL "$@"

# Keys
KeyGroup surfraw
Key $MODKEY-g      # Open web
	eval wi_surfraw_menu &
Key $MODKEY-Shift-g		# update elvis
	eval wi_update_eliv

KeyGroup session
Key $MODKEY-q			# close task
	eval wi_task_menu_close &
Key $MODKEY-o			# open task
	eval wi_task_menu_open &
Key $MODKEY-Shift-q    		# close session
	eval wi_session_close_menu &
Key $MODKEY-Shift-o		# open session
	eval wi_session_open_menu &

KeyGroup additional functionality for tags
Key $MODKEY-Control-Shift-d	# remove path from tag
	eval wi_remove_path
Key $MODKEY-Shift-Return	# open term path 1
	eval wi_terminal_one &
Key $MODKEY-Control-Return	# open term path 2
	eval wi_terminal_two &
Key $MODKEY-Control-p		# pdf menu path 1
	eval wi_pdfmenu_one &
Key $MODKEY-Shift-p		# pdf menu paht 2
	eval wi_pdfmenu_two &
!
}

wi_update_elvi &


# vim:filetype=sh
