#!/bin/dash -f

. ~/.wmii-hg/session.sh

session_help() {
echo \
"
usage: 
   wmii-pdf file [file ..] 		open pdf(s)
   wmii-pdf help			print this help
"
}

( [ -z "$1" ] && session_help )
case $1 in
	help)		session_help;;
	*)
		while [ $# -ne 0 ]
		do
			ARG="$1"
			shift
			if [ "$ARG" != "open" ];then
				wi_tabbed_open_tab $WI_PDF "$(readlink -f "$ARG")"
			fi
		done
	;;
esac



# vim:filetype=sh
