#!/bin/dash -f

export WMII_TERM="urxvtc"

. session.sh

local_events () {
	cat <<'!'
# Events
Event DestroyTag
	wmiir remove "/lbar/$@"
	rm -rf "$(wmiir namespace)/$@"
Event OpenPDF
	wi_open_zathura "$@"
Event OpenURL
	wi_open_surf "$@"

# Keys
KeyGroup surfraw
Key $MODKEY-g      # Open web
	eval wi_srmenu &
Key $MODKEY-Shift-g		# update elvis
	eval wi_updateeliv

KeyGroup session
Key $MODKEY-q			# close task menu
	eval wi_task_close
Key $MODKEY-o			# open task menu
	eval wi_task_open
Key $MODKEY-Shift-q    		# close session menu
	eval wi_session_close_menu &
Key $MODKEY-Shift-o		# open session menu
	eval wi_session_open_menu &

KeyGroup additional functionality for tags
Key $MODKEY-Control-Shift-d	# remove path from tag
	eval wi_remove_path
Key $MODKEY-Shift-Return	# open term path 1
	eval wi_terminal_one &
Key $MODKEY-Control-Return	# open term path 2
	eval wi_terminal_two &
Key $MODKEY-Control-p		# pdf menu path 1
	eval wi_pdfmenu_one &
Key $MODKEY-Shift-p		# pdf menu paht 2
	eval wi_pdfmenu_two &
!
}

wi_updateelvi


# vim:filetype=sh
