#!/bin/dash -f

. ~/.wmii-hg/session.sh

session_help() {
echo \
"
usage: 
   wmii-session opentask <task>		open session from a task
   wmii-session closetask <task>	save session to task
   wmii-session open <name>		open a session template
   wmii-session close <name>		close and save a session template
   wmii-session save <name>             save a session template
   wmii-session projects		show project templates	
   wmii-session addpath			add current path to a session
   wmii-session removepath		remove a path from current tag
   wmii-session terminal1		open a terminal with first path
   wmii-session terminal2		open a terminal with second path
   wmii-session cloentag		creates a helpertag with same session
   wmii-session show			infos of current tag
   wmii-session help			print this help
"
}

case $1 in
	opentask)	wi_task_cli_open $2;;
	closetask)	wi_task_cli_close $2;;
	open)		wi_session_open $2;;
	close)		wi_session_close $2;;
        save)           wi_session_save $2;;
	projects)	wi_projects_show;;
	addpath)	wi_add_path;;
	removepath)	wi_remove_path;;
	terminal1)	wi_terminal_one;;
	terminal2)	wi_terminal_two;;
	clonetag)	wi_session_create_helpertag;;
	help)		session_help;;
	show)		wi_session_show;;
	*)		session_help;;
esac






# vim:filetype=sh
